#
# Defining a microservice feature set to runtime equivalent
#  - This file instructs DeployHub to deploy the docker 
#  - containers to k8s for the component versions and then 
#  - setup the istio routing
#
# [Application.Variant.Version]
#   Component-1 = Variant.Version
#   Component-2 = Variant.Version
#   .
#   .
#   Component-N = Variant.Version

DefaultDomain = "GLOBAL/BikeWorks Game/Street Bike/Bike"

[Application]
Name    = "Street Bike"
Variant = "BumbleBee"
Version = "1.2.3.0"
Inherit = "latest"

DeleteComponents = [
]

UpdateComponents = [
  ['bike-login',    'master','d195bab']
  ['bike-frontend', 'master','f076b09']
]
