#
# Defining a microservice feature set to runtime equivalent
#  - This file instructs DeployHub to deploy the docker 
#  - containers to k8s for the component versions and then 
#  - setup the istio routing
#
# [Application.Version]
#   Component-1 = Version (feature flag)
#   Component-2 = Version (feature flag)
#   .
#   .
#   Component-N = Version (feature flag)

["Feature to Users"]
   V1     = ["sally","bob", "sue","joe"]

[Bike.V1]
    bike-login       = "master"
    bike-frontend    = "master"    
    bike-frame       = "yellow"
    bike-seat        = "yellow"
    bike-front-wheel = "yellow"
    bike-rear-wheel  = "yellow"

[Bike.V2]
    bike-login       = "master"
    bike-frontend    = "master"    
    bike-frame       = "black"
    bike-seat        = "black"
    bike-front-wheel = "yellow"
    bike-rear-wheel  = "yellow" 

