#
# Defining a microservice feature set to runtime equivalent
#  - This file instructs DeployHub to deploy the docker 
#  - containers to k8s for the component versions and then 
#  - setup the istio routing
#
# [Application.Version]
#   Component-1 = Version (feature flag)
#   Component-2 = Version (feature flag)
#   .
#   .
#   Component-N = Version (feature flag)

["Feature to Users"]
  "Bumblebee"     = ["sally","bob","sue","joe"]

[Bike.Wasp]
    bike-login       = "master"
    bike-frontend    = "master"    
    bike-frame       = "yellow"
    bike-seat        = "black"
    bike-front-wheel = "yellow"
    bike-rear-wheel  = "yellow"

[Bike."Yellow Jacket"]
    bike-login       = "master"
    bike-frontend    = "master"    
    bike-frame       = "black"
    bike-seat        = "black"
    bike-front-wheel = "yellow"
    bike-rear-wheel  = "yellow" 

[Bike."Green Hornet"]
    bike-login       = "master"
    bike-frontend    = "master"    
    bike-frame       = "green"
    bike-seat        = "green"
    bike-front-wheel = "black"
    bike-rear-wheel  = "black"   
