apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bikeinfo
spec:
  hosts:
    - "*"
  gateways:
    - bikeinfo-gateway
  http:
  - match:
    - uri:
        prefix: '/users'      
    route:
    - destination:
        host: bike-login
        subset: version-1
  - match:
    - uri:
        prefix: '/getbikeframe'      
    route:
    - destination:
        host: bike-frame
        subset: version-1
  - match:
    - uri:
        prefix: '/getbikefrontwheel'      
    route:
    - destination:
        host: bike-front-wheel
        subset: version-1  
  - match:
    - uri:
        prefix: '/getbikerearwheel'      
    route:
    - destination:
        host: bike-rear-wheel
        subset: version-1
  - match:
    - uri:
        prefix: '/getbikeseat'      
    route:
    - destination:
        host: bike-seat
        subset: version-1                                            
  - match:
    - uri:
        regex: '.*'      
    route:
    - destination:
        host: bike-frontend
        subset: version-1
---